### ISSUE TITLE
No connector for [cloudtasks]

### ISSUE THREAD

**Issue by tsulatsitamim** [stackkit/laravel-google-cloud-tasks-queue#6]
Hi thanks for the awesome package.
I try to install in laravel ^7.0 but get no connector error.

![2020-12-08_08-50](https://user-images.githubusercontent.com/5946791/101428172-cae3b200-3932-11eb-8894-ee24c793e9ad.png)

did i missing installation step?
thanks

**Comment by marickvantuil** [comment]
Hm I can't reproduce this, with these commands:

```shell
composer create-project --prefer-dist laravel/laravel:^7.0 cloud-tasks-test
cd cloud-tasks-test
composer require stackkit/laravel-google-cloud-tasks-queue
```

Please tell me which steps you are taking. Also what does it say if you run `php artisan package:discover`?

**Comment by tsulatsitamim** [comment]
I try to install other several custom queue driver:
1. `kainxspirits/laravel-pubsub-queue` same error
2. `dusterio/laravel-aws-worker` no error

After analyzing vendor frame, itsgoingd/clockwork make the error.
![2020-12-09_08-57](https://user-images.githubusercontent.com/5946791/101563939-c683cb80-39fc-11eb-8147-3c7438449bbd.png)

**Comment by marickvantuil** [comment]
Thnx I could reproduce the issue.

Clockwork is registered before Cloud Tasks is, which is why you are seeing this error.

Because Laravel auto registers service providers, I believe there is no way for me to specify ours should register before Clockwork's. The preferred 'Laravel way' to solve this is to not discover these packages and register them manually (in the right order):

`composer.json`
<img width="454" alt="Screenshot 2020-12-09 at 22 19 51" src="https://user-images.githubusercontent.com/647007/101688867-efdc4000-3a6c-11eb-9e8e-31e21f198edd.png">

`config/app.php`
<img width="624" alt="Screenshot 2020-12-09 at 22 19 56" src="https://user-images.githubusercontent.com/647007/101688884-f4085d80-3a6c-11eb-854c-738688c08195.png">

Alternatively you could add this to `bootstrap/app.php` but I don't know if it's really the best solution:

<img width="841" alt="Screenshot 2020-12-09 at 22 20 05" src="https://user-images.githubusercontent.com/647007/101689065-329e1800-3a6d-11eb-9d7e-e4d1322ad2d7.png">

**Comment by tsulatsitamim** [comment]
Thank you for the solution, so helpful.

**Comment by marickvantuil** [comment]
No problem 👍
