### ISSUE TITLE
Server error (http 500) on empty request

### ISSUE THREAD

**Issue by RazorMeister** [stackkit/laravel-google-cloud-tasks-queue#66]
Hello,

when sending empty request to handler url (http://127.0.0.1/handle-task) using for example Postman, there is exception thrown which results in http 500 error. I think that there should be some request validation (for example checking if request has all required headers: https://cloud.google.com/tasks/docs/creating-http-target-tasks#handler). If request is not valid should be shown some 422 or even 404 to somehow hide this endpoint from other people trying to mess with our app. 

What do you think about it?

**Comment by marickvantuil** [comment]
@RazorMeister Thnx for reporting. I have added some validation for the request data (and headers) that his package needs in order to work correctly. In debug mode it will show the validation errors (422 response) and with debug mode off it will return a 404 response. I'm not 100% happy with it yet, because when debug mode is off, it will just fail silently and there is no way to get notified (in a production app for example). So might end up changing it a bit later, but for now it validates the data at least :-)

Also, even with this 404 response, potential abusers could know this package is installed by calling the `handle-task` route through a `GET` request

<img width="670" alt="Screenshot 2022-09-02 at 18 28 15" src="https://user-images.githubusercontent.com/647007/188198618-f8913616-793a-4e04-a558-4dc39741e803.png">


Laravel will show a 405 Method Not Allowed, which kind of reveals the API call is available through other methods. But seems unlikely to me that this will actually cause problems.

(this was also added in `v3.2.1`)
