### ISSUE TITLE
Memory exhausted 

### ISSUE THREAD

**Issue by Kyon147** [stackkit/laravel-google-cloud-tasks-queue#80]
First of thanks for creating this awesome package! 

Just wondered if you'd encountered this before. I'm running some jobs that get pushed cloud tasks and then to a Google cloud run container.

The job is only uploading 250 rows but it seems to be swallowing all the memory on the container no matter what the size.

It does happen locally only when pushing the job through Google cloud tasks.

Any insight would be appreciated!

**Comment by marickvantuil** [comment]
Thank you!

That's very weird, as far as I know there is nothing in this package that could be using a lot of memory. I did a quick check with XDebug Profiler and found nothing that stood out. A basic job processed using the Cloud Tasks queue driver took 28 MB in total (entire Laravel request), of which 4.91% was this package (TaskHandler processing the task) which is around 1.4 MB.

<img width="966" alt="Screenshot 2022-11-19 at 13 55 39" src="https://user-images.githubusercontent.com/647007/202851950-7883347e-2627-4608-9ecd-a6dd9a0e3fe0.png">

Maybe you could try and poke around with XDebug profiling, or [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar)?

**Comment by Kyon147** [comment]
Hey @marickvantuil 

Thanks for coming back to me - it could be an issue with Cloud Run itself, as logging out memory usage in the jobs they are like 8MB and then after about 4/5 jobs the container runs out of memory.

I'm wondering if the on-going" live container that is getting the new job, is not cleaning up the memory properly from the last job and the container itself it running out as killing the process.

Have you ever experienced something like this when running a lot of jobs?

**Comment by Kyon147** [comment]
Update, it looks like it was an internal issue on Google's end as I opened a support ticket and it started working without any changes on my end.

Still would love to know about the should be unique though as that is defo not working.

**Comment by marickvantuil** [comment]
That's good to hear!!

Just checked ShouldBeUnique, and even though I haven't used it myself, it does seem to be working:


https://user-images.githubusercontent.com/647007/203134318-1b13f0fa-3289-445c-8afd-4be5b5bc7bb5.mp4



What's happening:
First attempt: dispatching a job twice without ShouldBeUnique: there are two dispatches and two 'handle-task' responses.
Second attempt: dispatching the same job with ShouldBeUnique: there are still two dispatches, but only one 'handle-task' response.

It seems to use the cache driver to store a lock on the job. Perhaps it's not working if the cache driver is set to `file` (the default) since Cloud Run could spin up multiple containers, each having their own cache directory? Otherwise I don't see why it wouldn't work. Let me know!

**Comment by marickvantuil** [comment]
> When I have tried in the past, the jobs never end up onto the queue.

Very weird! Haven't seen that happen 🤔. Definitely try again with the newest version!

**Comment by marickvantuil** [comment]
@Kyon147 Hi, did you manage to get some more info?

**Comment by Kyon147** [comment]
Hey @marickvantuil 

Yeah in the end it was a bug in cloud run on Google's side. So after a lot of debugging it was on their side 😅

Thanks for following up!
